services:
  - type: web
    name: phone-screen-damage-detection
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python3.10
